package com.aerozhonghuan.hongyan.producer.dao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.aerozhonghuan.hongyan.producer.dao.beans.UserBean;
import com.aerozhonghuan.hongyan.producer.dao.beans.Entity1;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig entity1DaoConfig;

    private final UserBeanDao userBeanDao;
    private final Entity1Dao entity1Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        entity1DaoConfig = daoConfigMap.get(Entity1Dao.class).clone();
        entity1DaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        entity1Dao = new Entity1Dao(entity1DaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(Entity1.class, entity1Dao);
    }
    
    public void clear() {
        userBeanDaoConfig.clearIdentityScope();
        entity1DaoConfig.clearIdentityScope();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public Entity1Dao getEntity1Dao() {
        return entity1Dao;
    }

}
